import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import TanstackProvider from '@/providers/tanstack.provider';
import NextAuthProvider from '@/providers/next-auth.provider';
import { Toaster } from '@/components/ui/toaster';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={(cn(inter.className), 'bg-gray-100')}>
        <TanstackProvider>
          <NextAuthProvider>{children}</NextAuthProvider>
        </TanstackProvider>
        <Toaster />
      </body>
    </html>
  );
}
